### ISSUE TITLE
A Guide for Installing Dependencies

### ISSUE THREAD

**Issue by mmtftr** [kcroker/dpsprep#5]
Personally, I've had problems getting all the dependencies on my ubuntu 18.04 LTS vm. I think better information on which dependencies should be installed would make using this python program easier. I'm not sure if this is actively maintained so I'll leave this issue here as it is, and if I manage to install the dependencies make a pull request with my process. Just wanted to let you know about this.

**Comment by MMDF** [comment]
Especially pdftk and pdfbeads caused me some problems. Pdftk is not present in bionic, had to add xenial or compile manually. Pdfbeads had me installing ruby-dev packages to compile nokogiri native extensions. Other than that, I had to install every mentioned package that was present in bionic before I had all the CLI tools required for dpsprep. I really liked the program itself but I don't think referring to stackoverflow questions for dependencies is a good idea for this project. Especially considering that some of the dependencies are no longer actively maintained.

**Comment by kcroker** [comment]
Sorry for the delay in response.  I've not updated the project in awhile,
so I can try to sit down and do a fresh install on a Devuan ASCII 2.0
machine and see what needs tweaking.  There might also be new tools at this
point, I originally wrote this 5 years ago.

Installing pdftk on any Ubuntu system should be trivial, not sure why that
would have changed.  No idea what xenial or bionic are.  Pdfbeads was
annoying 5 years ago, especially because I don't natively use anything else
in Ruby.  I suspect that its still annoying for this reason.

**Comment by MMDF** [comment]
Well I guess the fault is with ubuntu package manager people, they have pdftk on 20.04(focal) and 16.04(xenial) version package repositories but not in 18.04(bionic) for some reason.

Also maybe multithreading this might be a good idea(Using 10~20 workers which do all three processes for the page in one go maybe?). I can implement everything in nodeJS but i dont know how this works (dont know djvu and pdf specs).

**Comment by v--** [comment]
I know the issue is old. I'm writing this for future generations.

I believe the [asyncio subprocess API](https://docs.python.org/3/library/asyncio-subprocess.html) is perfect for handling multiple subprocesses, and it has a cleaner API than node's child_process. I might get to it, but that would require rewriting the project and I do not have the time to do that right now.

As for installing, the AUR package https://aur.archlinux.org/packages/dpsprep-git/ recursively lists all necessary dependencies, which is I believe the best we have as an installation guide.

**Comment by BrianZbr** [comment]
In the meantime I would love to at least know an OS and version this was tested with. The current readme mentions Ubuntu but doesn't specify version. I had no luck installing `djvu2hocr` on Ubuntu 20.04. Got a lot further with Raspbian 9.13 but Ruby was too old there for `pdfbeads`.

**Comment by v--** [comment]
It works on Arch when installing from AUR with the modification I mentioned applied. Should be the same with Ubuntu if you manage to resolve the dependencies listed in the AUR package.

**Comment by kcroker** [comment]
I'm super stoked that the tool is still useful to people, I'm sorry I'm so
swamped right now professionally that I can't pivot to addressing these
issues.  I suspect that with how much Python 3 has matured over the past 7
years, it might be possible to achieve a lot of things "in house" now, but
I'm not sure.  I start to free up in mid January ....

**Comment by BrianZbr** [comment]
I've started working on a Dockerfile to see if I can get this working in a container. I've experimented both with Arch and various Ubuntu versions so far but keep running into various issues with each. @v--: That dpsprep-git package looks promising but how do I install it? I'm not very experienced with Arch and could use a hint. I've tried building it with makepkg but it seems like I may need ocrodjvu first and that requires python2.

**Comment by v--** [comment]
@BrianZbr How do you install via AUR? The idea is that you use your own account to run `makepkg` and generate a package. Refer to [the wiki article](https://wiki.archlinux.org/title/Makepkg#Signature_checking). I recently installed djvuocro along with Python 2 from the AUR packages and everything went smoothly.

**Comment by BrianZbr** [comment]
@v-- Doing this in Docker makes it a little more complicated because default unix user is root and can't run makpkg directly. 

One approach I've tried:

```
sudo -u builduser bash -c 'cd ~ && git clone https://aur.archlinux.org/python2.git &&\
cd python2 && makepkg -s --noconfirm --nocheck --skippgp'
``` 

The install process is very long with lots of output and eventually ends like this:

```
==> Tidying install...
  -> Removing libtool files...
  -> Purging unwanted files...
  -> Removing static library files...
  -> Stripping unneeded symbols from binaries and libraries...
  -> Compressing man and info pages...
==> Checking for packaging issues...
==> WARNING: Package contains reference to $srcdir
usr/lib/python2.7/config/Makefile
usr/lib/python2.7/config/python.o
usr/lib/python2.7/_sysconfigdata.pyo
usr/lib/python2.7/lib-dynload/pyexpat.so
usr/lib/python2.7/lib-dynload/gdbm.so
usr/lib/python2.7/lib-dynload/_ssl.so
usr/lib/python2.7/lib-dynload/array.so
usr/lib/python2.7/_sysconfigdata.py
usr/lib/python2.7/_sysconfigdata.pyc
usr/lib/libpython2.7.so.1.0
==> Creating package "python2"...
  -> Generating .PKGINFO file...
  -> Generating .BUILDINFO file...
  -> Generating .MTREE file...
  -> Compressing package...
==> Leaving fakeroot environment.
==> Finished making: python2 2.7.18-7 (Tue Nov  1 00:02:33 2022)
```
However, I don't see any evidence that python2 is actually installed. When I then try to then install `ocrodjvu` with a similar method, it lists python2 among dependencies not found.

I can install `packer` with this `makepkg` approach, but if I try to `packer -S ocrodjvu` or `packer -S python2`, it prompts me to edit the relevant PKGBUILD file(s) and I have no idea what I'm doing with those.

Maybe if I try to spin up a full Arch VM I'll have better luck but it would be nice to find a solution in Docker. I'll keep messing around I guess.

**Comment by v--** [comment]
@BrianZbr The package is not installed because you haven't installed it. `makepkg` produces a package within the build directory. Not you need to install it via `pacman -U <file_name>`. Or, more simply, use `makepkg`'s `--install` option.

There are wrapper scripts for installing packages from the AUR that try to handle basic security and dependency management. You can look them up in the wiki. I personally use [Aura](https://github.com/fosskers/aura). The official repositories don't contain AUR helpers, so you have to follow the installation instructions (there seem to be very simple ones for Aura). I have an `aura-bin` package in [my personal repository](https://ivasilev.net/pacman) if that helps.

**Comment by BrianZbr** [comment]
These look like helpful tips, thanks @v-- !

**Comment by BrianZbr** [comment]
Here's the Dockerfile I've been working on and I believe it covers all the required dependencies: https://gist.github.com/BrianZbr/9105952e93ae84dbcb791548c20d07b6

However, I've tried processing several files now and keep getting stuck with the following:

```
OCRd text extracted.
/usr/lib/ruby/gems/3.0.0/gems/pdfbeads-1.1.3/lib/pdfbeads/pdfpage.rb:412:in `initialize': undefined method `has_key?' for nil:NilClass (NoMethodError)
	from /usr/lib/ruby/gems/3.0.0/gems/pdfbeads-1.1.3/bin/pdfbeads:219:in `new'
	from /usr/lib/ruby/gems/3.0.0/gems/pdfbeads-1.1.3/bin/pdfbeads:219:in `<top (required)>'
	from /usr/sbin/pdfbeads:25:in `load'
	from /usr/sbin/pdfbeads:25:in `<main>'

NOTE: There was a problem beading, see above output.
```
Forgive me if this is not actually related to the present issue, but I'm thinking maybe I need a different version of `pdfbeads` or something? Any suggestions?

**Comment by v--** [comment]
@BrianZbr The following are Arch packages:

```
Name            : pdfbeads
Version         : 1.1.3-2
```

```
Name            : ruby-rmagick
Version         : 4.2.6-1
```

**Comment by BrianZbr** [comment]
Thanks @v--. So for every single requirement you just installed the current Arch package, nothing with `gem` or `pip`?

**Comment by v--** [comment]
@BrianZbr By convention, Arch people make packages for python with a `python-` prefix, and similarly for other languages - refer to [this wiki page](https://wiki.archlinux.org/title/Arch_package_guidelines#Additional_guidelines). The point is that you can rely entirely on the AUR to install whatever you want without knowing anything about `pip` or `gem`.

I cannot comment on your particular issues because I have never encountered them. You have have PATH issues, you may have encountered an unfinished PKGBUILD script. Or it may be something specific to Docker.

You can use [Poetry](https://python-poetry.org) for the Python dependencies and `gem` for the Ruby dependencies. It should be a better cross-platform solution than AUR.

**Comment by v--** [comment]
@BrianZbr I just pushed an `ocrodjvu-python3-git` package to the AUR. It is based on a port of ocrodjvu  which makes the Python 2 dependency obsolete.

**Comment by BrianZbr** [comment]
@v-- Thanks for the update, I've finally installed `ocrodjvu-python3-git` via `yay` on a fresh Arch VM (Docker won't work, some packages want systemd). 

Install seemed OK and running the app got pretty far but I'm hitting this error that I've seen before and have not found a fix for:

```
/usr/lib/ruby/gems/3.0.0/gems/pdfbeads-1.1.3/lib/pdfbeads/pdfpage.rb:412:in `initialize': undefined method `has_key?' for nil:NilClass (NoMethodError)
        from /usr/lib/ruby/gems/3.0.0/gems/pdfbeads-1.1.3/bin/pdfbeads:219:in `new'
        from /usr/lib/ruby/gems/3.0.0/gems/pdfbeads-1.1.3/bin/pdfbeads:219:in `<top (required)>'
        from /usr/bin/pdfbeads:25:in `load'
        from /usr/bin/pdfbeads:25:in `<main>'
```

Running `pdfbeads -v` says `pdfbeads RMagick 4.2.6`.

**Comment by v--** [comment]
@BrianZbr Looking at the source code of pdfbeads, seems like Magick isn't initialized and pdfbreads handles that really badly. Do you have `ruby-rmagick` installed?

**Comment by v--** [comment]
@BrianZbr I just added all required ruby packages to my repository. Try running `pacman -S dpsprep-git` and dependencies should get resolved automatically. This also confirms that all AUR build scripts are valid.

**Comment by BrianZbr** [comment]
@v-- I guess I need to add your repository to my pacman.conf to make that work? When I try that I get stuck on:

```
error: key "B77A3C8832838F1F80ADFD7E1D0507B417DAB671" could not be looked up remotely
error: database 'ivasilev' is not valid (invalid or corrupted database (PGP signature))
```

**Comment by v--** [comment]
@BrianZbr Yes. My website features the exact two lines you need for that.

You may need to fetch my GPG key via `pacman-key` (look up the arch wiki) or disable package signature checking for my repo.

**Comment by BrianZbr** [comment]
@v-- With `SigLevel = Never` I was able to proceed. Now `pacman -S dpsprep-git` runs normally but doesn't seem to add any new packages, shows a warning `warning: dpsprep-git-r17.3d657d7-1 is up to date -- reinstalling` and I see no change otherwise. I also tried uninstalling and reinstalling but it's not finding any new dependencies.

**Comment by v--** [comment]
@BrianZbr They you have everything installed. You can try `pacman -Rcs dpsprep-git` in order to remove packages related to `dpsprep-git`, and then try installing the package again.

**Comment by BrianZbr** [comment]
@v-- I tried `pacman -Rcs dpsprep-git` and that seemed to remove a lot of packages as I would expect, but then when I tried to `pacman -S dpsprep-git` it would not proceed because it couldn't resolve `python-sexpdata`. I was able to install that package with yay and proceed from there, but then I'm still back to the pdfbeads error I reported this morning.

**Comment by v--** [comment]
@BrianZbr I'm afraid I cannot help you. You can try to debug the ruby code yourself and report to RMagick if you find something wrong.

**Comment by kcroker** [comment]
The modernized version by @v-- obsoletes this issue

**Comment by BrianZbr** [comment]
What version? Can you share a link?

**Comment by kcroker** [comment]
Just git pull the master branch.  @v-- did a nice rewrite so that
everything leans on Python dependencies, and is managed there.

**Comment by BrianZbr** [comment]
Nice, yes! Can confirm that after `apt install djvulibre-bin libdjvulibre-dev` this worked for me on Ubuntu. Thanks all.
